import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Books Calculator by mr",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="antialiased tracking-tight">
            {children}

      </body>

    </html>
  );
}
